export const EV = {
  // get the data (UV/W low/high) for an instrument
  PAGE_CHANGED: 'PAGE_CHANGED',
  PAGE_TITLE_CHANGED: 'PAGE_TITLE_CHANGED',
  RESET_SEARCH_TERMS: 'RESET_SEARCH_TERMS',
  CHANGED_SEARCH_TERMS: 'CHANGED_SEARCH_TERMS',
  CHANGED_BATCH: 'CHANGED_BATCH',
};
