export const EV = {
  // get the data (UV/W low/high) for an instrument
  BREADCRUMB_CHANGED: 'BREADCRUMB_CHANGED',
  RESET_SEARCH_TERMS: 'RESET_SEARCH_TERMS',
  CHANGED_SEARCH_TERMS: 'CHANGED_SEARCH_TERMS',
  CHANGED_BATCH: 'CHANGED_BATCH',
};
